### Q_1: create 2D-array that contain even numbers between 0-18...??

In [1]:
import numpy as np
print(np.arange(0, 19, 2))

[ 0  2  4  6  8 10 12 14 16 18]


### Q_2: Replace the negative values with 0 in random array that has value in range (-6,6)

In [5]:
tmp = np.random.randint(-6, 7, 10)
print(tmp)
tmp[tmp < 0] = 0
print(tmp)

[ 5 -2  6 -6 -3  1  5 -3 -5  5]
[5 0 6 0 0 1 5 0 0 5]


### Q_3 :  How to compute ((A+B)*(-A/2)) ?  where A,B random array

In [7]:
A = np.random.random((2,2))
B = np.random.random((2,2))
print((A+B)*(-A/2))

[[-0.02681376 -0.31172755]
 [-0.25217927 -0.26956982]]


### Q_4: How to concatenate two arrays horizontally..?

In [20]:
A = np.arange(1, 6)
print(A)
print(A.shape)
A = A.reshape(1, 5)
B = np.arange(6, 11)
B = B.reshape(1, 5)
print(B)
print(np.concatenate((A, B), axis=1))

[1 2 3 4 5]
(5,)
[[ 6  7  8  9 10]]
[[ 1  2  3  4  5  6  7  8  9 10]]


#### Q_5: Create a array vector of size 3x3 and sort values in Its columns

In [30]:
tmp = np.random.randint(0, 10, 10).reshape(2, 5)
print(tmp)

tmp.sort(axis=0)
print(tmp)

[[5 4 4 6 0]
 [5 5 8 2 8]]
[[5 4 4 2 0]
 [5 5 8 6 8]]
