In [1]:
import numpy as np

a = np.array([[1, 2, 3],[4,5,6]],dtype=np.float32)
print(a)
print(a.shape)
print(a.ndim)
print(a.size)

[[1. 2. 3.]
 [4. 5. 6.]]
(2, 3)
2
6


In [ ]:
a = np.ones((3,3))
print(a)
b = np.zeros((3,3))
print(b)
c = np.eye(3)
print(c)
d = np.diag(np.array([1,2,3,4]))
print(d)
g = np.random.rand(4,4)
print(g)
h= np.random.randn(4,4)
print(h)
z = np.arange(0,10,2)
print(z)
r = np.linspace(0,10,5)
print(r)

#create lin space matrix
x = np.linspace(0,10,25)
print(x)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]
[[0.91104757 0.92304804 0.38702089 0.4494813 ]
 [0.3640215  0.65355622 0.81380122 0.67282683]
 [0.53464398 0.83325634 0.20024184 0.8026951 ]
 [0.65943287 0.5080335  0.410658   0.36675358]]
[[ 0.08317138  2.38463279 -1.30756166 -0.99823801]
 [-0.87829164  0.03308207  1.78246646  0.58483206]
 [ 0.10613321 -1.60978974  0.69452432  1.80719978]
 [-1.02724995  0.09076373 -0.24923074  0.68306201]]
[0 2 4 6 8]
[ 0.   2.5  5.   7.5 10. ]
[ 0.          0.41666667  0.83333333  1.25        1.66666667  2.08333333
  2.5         2.91666667  3.33333333  3.75        4.16666667  4.58333333
  5.          5.41666667  5.83333333  6.25        6.66666667  7.08333333
  7.5         7.91666667  8.33333333  8.75        9.16666667  9.58333333
 10.        ]


In [23]:
x.reshape(5,5)

array([[ 0.        ,  0.41666667,  0.83333333,  1.25      ,  1.66666667],
       [ 2.08333333,  2.5       ,  2.91666667,  3.33333333,  3.75      ],
       [ 4.16666667,  4.58333333,  5.        ,  5.41666667,  5.83333333],
       [ 6.25      ,  6.66666667,  7.08333333,  7.5       ,  7.91666667],
       [ 8.33333333,  8.75      ,  9.16666667,  9.58333333, 10.        ]])

In [2]:
a = np.array([[1,2,3],[4,5,6]])
print(a)
b = np.array([[1,2,3],[4,5,6]])
print(b)
print(np.concatenate((a,b),axis=1))

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]
[[1 2 3 1 2 3]
 [4 5 6 4 5 6]]


In [3]:
a = np.array([[1,2,3],[4,5,6]])
print(a)
b = np.array([[1,2,3],[4,5,6]])
print(b)
print(np.concatenate((a,b),axis=0))

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]


In [29]:
print(a.dtype)
print(a.astype(np.float16))

int64
[[1. 2. 3.]
 [4. 5. 6.]]


In [30]:
np.zeros_like(a)

array([[0, 0, 0],
       [0, 0, 0]])

In [35]:
A = np.array([[1,2],[3,4]])
print(A)
print(A.reshape(1,4))
print(A.reshape(4,1))
print(A.reshape(4,-1))
print(A.reshape(3,-1))

[[1 2]
 [3 4]]
[[1 2 3 4]]
[[1]
 [2]
 [3]
 [4]]
[[1]
 [2]
 [3]
 [4]]


ValueError: cannot reshape array of size 4 into shape (3,newaxis)

In [40]:
B = np.array([[5,6],[7,8],[9,10]])
print(B.reshape(2,-1))
print(B.reshape(1,-1))
print(B.reshape(-1,2))

[[ 5  6  7]
 [ 8  9 10]]
[[ 5  6  7  8  9 10]]
[[ 5  6]
 [ 7  8]
 [ 9 10]]


In [43]:
print(B.reshape(1,2,3))
print(B.reshape(2,1,3))
print(B.reshape(2,1,3).shape)

[[[ 5  6  7]
  [ 8  9 10]]]
[[[ 5  6  7]]

 [[ 8  9 10]]]
(2, 1, 3)


In [4]:
A = np.array([[1,2],[3,4],[5,6]])
print(A)
print(A.T)

[[1 2]
 [3 4]
 [5 6]]
[[1 3 5]
 [2 4 6]]


In [10]:
mat = np.arange(1,26).reshape(5,5)
print(mat)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [50]:
# Arithmetic operations
print(mat + mat)
print(mat - mat)
print(mat * mat)

[[ 2  4  6  8 10]
 [12 14 16 18 20]
 [22 24 26 28 30]
 [32 34 36 38 40]
 [42 44 46 48 50]]
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
[[  1   4   9  16  25]
 [ 36  49  64  81 100]
 [121 144 169 196 225]
 [256 289 324 361 400]
 [441 484 529 576 625]]


In [52]:
# scalar operations
print(mat + 100)
print(mat - 100)
print(mat * 100)

[[101 102 103 104 105]
 [106 107 108 109 110]
 [111 112 113 114 115]
 [116 117 118 119 120]
 [121 122 123 124 125]]
[[-99 -98 -97 -96 -95]
 [-94 -93 -92 -91 -90]
 [-89 -88 -87 -86 -85]
 [-84 -83 -82 -81 -80]
 [-79 -78 -77 -76 -75]]
[[ 100  200  300  400  500]
 [ 600  700  800  900 1000]
 [1100 1200 1300 1400 1500]
 [1600 1700 1800 1900 2000]
 [2100 2200 2300 2400 2500]]


In [7]:
# Matrix multiplication
ran_mat = np.random.randint(1,100,5).reshape(5,1)
print(ran_mat)
print(mat.dot(ran_mat))

[[97]
 [99]
 [96]
 [ 4]
 [ 6]]
[[ 629]
 [2139]
 [3649]
 [5159]
 [6669]]


In [56]:
# logical operations
print(mat > 10)

[[False False False False False]
 [False False False False False]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]]


In [57]:
mat[mat > 10]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25])

In [13]:
tmp = np.arange(26,51).reshape(5,5)
mat = mat.astype(np.float32)
print(tmp)
mat /= tmp
print(mat)

[[26 27 28 29 30]
 [31 32 33 34 35]
 [36 37 38 39 40]
 [41 42 43 44 45]
 [46 47 48 49 50]]
[[0.03846154 0.07407407 0.10714286 0.13793103 0.16666667]
 [0.19354838 0.21875    0.24242425 0.2647059  0.2857143 ]
 [0.30555555 0.3243243  0.34210527 0.35897437 0.375     ]
 [0.3902439  0.4047619  0.41860464 0.4318182  0.44444445]
 [0.45652175 0.4680851  0.47916666 0.48979592 0.5       ]]


In [ ]:
print(np.sqrt(mat))
print(np.exp(mat))
print(np.sin(mat))

[[1.0190493 1.0363754 1.0522085 1.0667385 1.0801234]
 [1.0924964 1.10397   1.1146408 1.1245915 1.1338934]
 [1.1426091 1.150793  1.1584927 1.1657505 1.172604 ]
 [1.1790861 1.1852266 1.1910518 1.196586  1.2018504]
 [1.2068645 1.2116456 1.2162099 1.220572  1.2247449]]
[[2.8248677 2.9272811 3.025701  3.1203055 3.2112703]
 [3.298766  3.382956  3.4640007 3.5420508 3.6172507]
 [3.6897385 3.7596443 3.8270922 3.8921993 3.9550767]
 [4.0158296 4.0745564 4.1313515 4.186303  4.239496 ]
 [4.2910085 4.3409142 4.3892865 4.43619   4.481689 ]]
[[0.8616244  0.87914926 0.89442456 0.90776753 0.919445  ]
 [0.9296819  0.9386691  0.9465686  0.9535189  0.9596386 ]
 [0.9650294  0.96977925 0.973964   0.97764945 0.9808931 ]
 [0.9837446  0.9862479  0.98844117 0.99035805 0.99202824]
 [0.99347776 0.9947298  0.9958049  0.99672127 0.997495  ]]


In [22]:
# Indexing and slicing
mat = np.arange(1,26).reshape(5,5)
print(mat)
print(mat[0])
print(mat[2][4])
print(mat[[2,4],:])
mat[[2,4],:]=0
print(mat)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
[1 2 3 4 5]
15
[[11 12 13 14 15]
 [21 22 23 24 25]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [ 0  0  0  0  0]
 [16 17 18 19 20]
 [ 0  0  0  0  0]]


In [21]:
print(mat[2])
print(mat[4])
print(mat[[2,4]])

[11 12 13 14 15]
[21 22 23 24 25]
[[11 12 13 14 15]
 [21 22 23 24 25]]


In [75]:
# sum
print(mat.sum())
print(mat.sum(axis=0))
print(mat.sum(axis=1))

145
[23 26 29 32 35]
[15 40  0 90  0]


In [ ]:
print(mat.max())
print(mat.min())
print(mat.mean())

20
0
5.8


In [24]:
print(mat)
print(mat.argmax())

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [ 0  0  0  0  0]
 [16 17 18 19 20]
 [ 0  0  0  0  0]]
19


In [25]:
print(np.arange(0,19,2))

[ 0  2  4  6  8 10 12 14 16 18]


In [27]:
arr = np.random.randint(-6,7,10)
print(arr)
arr[arr <0]=0
print(arr)

[ 6 -4  2  5 -2  2 -4 -6 -4 -1]
[6 0 2 5 0 2 0 0 0 0]


In [28]:
A = np.random.randint(1,10,9).reshape(3,3)
print(A)
B = np.random.randint(1,10,9).reshape(3,3)
print(B)

print((A+B)*(-A/2))

[[5 6 4]
 [9 8 4]
 [4 5 6]]
[[4 4 7]
 [6 1 6]
 [1 9 3]]
[[-22.5 -30.  -22. ]
 [-67.5 -36.  -20. ]
 [-10.  -35.  -27. ]]


In [29]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[7,8,9],[10,11,12]])
print(np.concatenate((arr1,arr2),axis=1))

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [32]:
arr = np.random.randint(0,10,9).reshape(3,3)
print(arr)
arr.sort(axis=0)
print(arr)

[[4 1 8]
 [7 8 5]
 [9 3 7]]
[[4 1 5]
 [7 3 7]
 [9 8 8]]
